Deployment: Dist id fetching

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -86,9 +86,15 @@ jobs:
       # Step 4 - Invalidate CloudFront cache
       - name: Invalidate CloudFront cache
         run: |
+          DISTRIBUTION_ID=$(aws --region ${REGION} cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionID'].OutputValue" --output text)
+          if [ -z "$DISTRIBUTION_ID" ]; then
+            echo "CloudFront distribution ID not found."
+            exit 1
+          fi
+          echo "Invalidating CloudFront distribution: $DISTRIBUTION_ID"
           aws cloudfront create-invalidation \
-            --distribution-id $STACK_NAME \
-            --paths "/*"
+            --distribution-id $DISTRIBUTION_ID \
+            --paths "/" "/*"
 
 # --------------------------
 # PROD DEPLOYMENT
